version: "3.8"
services:
  conversion-api:
    build:
      context: conversion_api
      target: builder
    container_name: conversion_api_app
    networks:
      - web_net
    ports:
     - "5000:5000"
    depends_on: 
      - db
  db: 
    container_name: conversion_db_pg
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: conversion
      POSTGRES_DB: conversion
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data
  redis:
    build:
      context: redis
      target: builder
    image: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379:0:redisultramegasecurepassword
    ports:
      - '8081:8081'
    depends_on:
      - 'redis'

networks:
    web_net:
        driver: bridge
       
volumes: 
  pg-data: 
    driver: local
  redisdata:


