version: "3.8"
services:
  cronjob:
      build: cronjob
      volumes:
        - ${PWD}/cronjob:/root
      command: ["sh", "-c", "cron && tail -f /var/log/cron.log"]
  conversion-api:
    build:
      context: conversion_api
    container_name: conversion_api_app
    networks:
      - web_net
    ports:
     - "5500:5000"
    depends_on: 
      - db
    volumes: 
      - ${PWD}/conversion_api:/app
  celery:
    build:
      context: conversion_api  
      dockerfile: mq.Dockerfile
    container_name: celery-app
    networks:
      - web_net    
    volumes: 
      - ${PWD}/conversion_api:/app
  db: 
    container_name: conversion_db_pg
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: conversion
      POSTGRES_DB: conversion
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data
  redis:
    container_name: redis
    build:
      context: redis 
    image: 'redis'
    networks:
      - web_net
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

networks:
    web_net:
        driver: bridge
       
volumes: 
  pg-data: 
    driver: local
  redisdata:


